title: 福音のマーメイド 〜福井ロコドル活動記〜
author: 足羽川永都
description: >
  福井のご当地アイドル「福音のマーメイド」のメンバーがインタビューに答えます。
  全員人間じゃないけど。
image: https://8amjp.github.io/site-icon.png
type: novel
card: summary
twitter_username: 8amjp
github_username:  8amjp
google_analytics: UA-41627578-3

# Build settings
markdown: kramdown
theme: minima
