title: 福音のマーメイド 〜福井ロコドル活動記〜
author: 8amjp
email: wakeup@8am.jp
<<<<<<< HEAD
description: >
  福井のご当地アイドル「福音のマーメイド」のメンバーがインタビューに答えます。
=======
description: > # this means to ignore newlines until "baseurl:"
  福井のご当地アイドル「福音のマーメイド」のメンバーがインタビューに答えます。  
>>>>>>> 85471060b302db36f1f1c3789f3b495a64bcb70e
  全員人間じゃないけど。

catchphrase: プロデューサーさん、私でも、アイドル活動出来ますか……？

twitter_username: 8amjp
github_username:  8amjp

minima:
  date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
theme: minima
