title: 福音のマーメイド 〜福井ロコドル活動記〜
author: 足羽川永都
email: wakeup@8am.jp
description: >
  福井のご当地アイドル「福音のマーメイド」のメンバーがインタビューに答えます。
  全員人間じゃないけど。
catchphrase: >
  プロデューサーさん、私でも、アイドル活動出来ますか……？
twitter_username: 8amjp
github_username:  8amjp

minima:
  date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
theme: minima
