title: 福音のマーメイド 〜福井ロコドル活動記〜
author: 8amjp
description: >
  福井のご当地アイドル「福音のマーメイド」のメンバーがインタビューに答えます。
  全員人間じゃないけど。
  [コメディ、アイドル/連作短編]
index: auto

image: icon.png
type: novel
google_analytics: UA-41627578-3
twitter:
  username: 8amjp

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag